### PR TITLE
Internal sprucing up

### PR DESCRIPTION
**Pull request by djzort**
Swapped a few things:
LWP -> HTTP::Tiny, faster, smaller, less deps
Errors -> removed, deprecated upstream
XML::Bare -> XML::Fast, faster, smaller and less deps

Adjusted the test suite a bit, separated build and running deps.

I stopped short of swapping the build system to Dist::Zilla. I am happy to take comaint of this module if you like.

### CODE REVIEW

**Comment by pallotron** [comment]
wow, I haven't been using this for ages, like 7 years? :)
good to see people find it useful. I will look at your commits now and let you know.

**Comment by pallotron** [comment]
thanks!

**Comment by pallotron** [comment]
as for `comaint`, I am happy with the idea :)

**Comment by pallotron** [comment]
the thing is that last time I use CPAN was like 7 years ago :)
Need to refresh it in my mind

**Comment by pallotron** [comment]
Ok I got access to PAUSE, what's your user id so I can make you co maintainer?

**Comment by pallotron** [comment]
http://search.cpan.org/~djzort/ <-- this?

**Comment by djzort** [comment]
thats me.

**Comment by pallotron** [comment]
> Added DJZORT to co-maintainers of Monit::HTTP.
> Added DJZORT to co-maintainers of Monit::HTTP::API.

you are set!

**Comment by pallotron** [comment]
Feel free to send a PR to add you to README file.

**Comment by djzort** [comment]
Thanks for that

**Comment by djzort** [comment]
how would you feel about me adopting the module entirely?

**Comment by pallotron** [comment]
in CPAN? I prefer we stay like this for now :)
we will revisit.

**Pull request merged**
